# Workflow for deploying the portfolio website to GitHub Pages
name: Deploy Portfolio Website to GitHub Pages

on:
  # Trigger deployment on pushes to the main branch
  push:
    branches: ["main"]

  # Allow manual workflow dispatch from the Actions tab
  workflow_dispatch:

# Permissions for the GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, ensuring stability during updates
concurrency:
  group: "portfolio-pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Check out the latest code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Configure GitHub Pages environment
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # Upload the website's content as an artifact for deployment
      - name: Upload Portfolio Content
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Include all files in the repository

      # Deploy the content to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
